services:
  loadbalancer:
    build:
      context: ./loadbalancer
      dockerfile: Dockerfile
    container_name: loadbalancer
    depends_on:
      - svc1
      - svc2
    # image: joy7140/loadbalancer:v1.0.1
    ports:
      - "80:80"
    environment:
      - PORT=80
    networks:
      - svc-network
  svc1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    container_name: svc1
    # image: joy7140/svc1:v1.0.1
    depends_on:
     - svc2
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SVC2_URL=http://svc2:8000
    networks:
      - svc-network

  svc2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    container_name: svc2
    # image: joy7140/svc2:v1.0.1
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - svc-network

  svc3:
      build:
        context: ./service3
        dockerfile: Dockerfile
      container_name: svc3
      # image: joy7140/svc3:v1.0.1
      ports:
        - "8080:8080"
      environment:
        - PORT=8080
      networks:
        - svc-network

networks:
  svc-network:
    driver: bridge
