apiVersion: v1
kind: Service
metadata:
  name: service1-service
  namespace: devops
spec:
  selector:
    app: service1-deployment

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001 # NodePort for external access, can be accessed via <NodeIP>:30001

  type: NodePort