[project]
name = "service2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "joyshaha", email = "eee.joy.ckz@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
service2 = "service2:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
