apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3-deployment
spec:
  replicas: 1 # Adjusted the number of replicas to 3 for better availability

  selector:
    matchLabels:
      app: service3

  template:
    metadata:
      labels:
        app: service3

    spec:
      containers:
        - name: service3
          image: joy7140/svc3:v1.0.1

          ports:
            - containerPort: 8080 # Adjusted the container port to 3000 to match the application configuration

          imagePullPolicy: IfNotPresent


---

apiVersion: v1
kind: Service
metadata:
  name: service3-service
  # namespace: default
spec:
  selector:
    app: service3

  ports:
    - protocol: TCP
      port: 80
      # targetPort: 8080 # Adjusted the target port to 3000 to match the container port
      name: service3 # used to not change targetPort with changing containerPort

  # type: NodePort # Changed the service type NodePort to ClusterIP to allow internal communication within the cluster
  # type: LoadBalancer # Changed the service type to LoadBalancer to expose the service externally
  type: ClusterIP # for internal communication


# config map or secret can be used for environemnt passing