apiVersion: v1
kind: Service

metadata:
  name: service2-service
  namespace: devops

spec:
  selector:
    app: service2-deployment

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001 # NodePort for external access, can be accessed via <NodeIP>:30001

  type: NodePort